CREATE TABLE df_test_table (
	STORE_NO INT64,
	COM_CD_y INT64,
	CON_UPC_NO_Y INT64,
	CAS_UPC_NO INT64,
	CAS_DSC_TX STRING(MAX),
	SHF_ALC_QY STRING(MAX),
	SHF_NO INT64,
	SHF_MIN_QY INT64,
	AIL_ORN_CD STRING(MAX),
	AIL_NO INT64,
	AIL_LOC_CD STRING(MAX),
	t TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
) PRIMARY KEY (AIL_LOC_CD);
